/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { INFTOracle } from "./INFTOracle";
export type { LendingProtocol } from "./LendingProtocol";
export type { MockERC20 } from "./MockERC20";
export type { MockNFT } from "./MockNFT";
export type { MockOracle } from "./MockOracle";
