/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { INFTOracle__factory } from "./INFTOracle__factory";
export { LendingProtocol__factory } from "./LendingProtocol__factory";
export { MockERC20__factory } from "./MockERC20__factory";
export { MockNFT__factory } from "./MockNFT__factory";
export { MockOracle__factory } from "./MockOracle__factory";
