/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  INFTOracle,
  INFTOracleInterface,
} from "../../contracts/INFTOracle";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "nft",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "getFloorPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class INFTOracle__factory {
  static readonly abi = _abi;
  static createInterface(): INFTOracleInterface {
    return new Interface(_abi) as INFTOracleInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): INFTOracle {
    return new Contract(address, _abi, runner) as unknown as INFTOracle;
  }
}
